export const GET_TRENDINGS_REQUEST = 'GET_TRENDINGS_REQUEST'
export const GET_TRENDINGS_SUCCESS = 'GET_TRENDINGS_SUCCESS'
export const GET_TRENDINGS_FAIL = 'GET_TRENDINGS_FAIL'

export const GET_LATEST_MOVIES = 'GET_LATEST_MOVIES';

export const GET_MOVIES_REQUEST = 'GET_MOVIES_REQUEST'
export const GET_MOVIES_SUCCESS = 'GET_MOVIES_SUCCESS'
export const GET_MOVIES_FAIL = 'GET_MOVIES_FAIL'

export const GET_MOVIES_GENRES = 'GET_MOVIES_GENRES'
export const GET_LANGUAGES = 'GET_LANGUAGES'


export const TOP_RATED_MOVIES_REQUEST = 'TOP_RATED_MOVIES_REQUEST'
export const TOP_RATED_MOVIES_SUCCESS = 'TOP_RATED_MOVIES_SUCCESS'
export const TOP_RATED_MOVIES_FAIL = 'TOP_RATED_MOVIES_FAIL'

export const MOVIE_DETAILS_REQUEST = 'MOVIE_DETAILS_REQUEST'
export const MOVIE_DETAILS_SUCCESS = 'MOVIE_DETAILS_SUCCESS'
export const MOVIE_DETAILS_FAIL = 'MOVIE_DETAILS_FAIL'

export const GET_MOVIE_CREDITS = 'GET_MOVIE_CREDITS'
export const GET_MOVIE_VIDEOS = 'GET_MOVIE_VIDEOS'
export const GET_MOVIE_IMAGES = 'GET_MOVIE_IMAGES'
export const GET_SIMILAR_MOVIES = 'GET_SIMILAR_MOVIES'

export const SEARCH_DATA_REQUEST = 'SEARCH_DATA_REQUEST'
export const SEARCH_DATA_SUCCESS = 'SEARCH_DATA_SUCCESS'
export const SEARCH_DATA_FAIL = 'SEARCH_DATA_FAIL'
