export const GET_LATEST_TVSHOWS = 'GET_LATEST_TVSHOWS'

export const GET_TVSHOWS_REQUEST = 'GET_TVSHOWS_REQUEST'
export const GET_TVSHOWS_SUCCESS = 'GET_TVSHOWS_SUCCESS'
export const GET_TVSHOWS_FAIL = 'GET_TVSHOWS_FAIL'

export const GET_TVSHOWS_GENRES = 'GET_TVSHOWS_GENRES'

export const TOP_RATED_TVSHOWS_REQUEST = 'TOP_RATED_TVSHOWS_REQUEST'
export const TOP_RATED_TVSHOWS_SUCCESS = 'TOP_RATED_TVSHOWS_SUCCESS'
export const TOP_RATED_TVSHOWS_FAIL = 'TOP_RATED_TVSHOWS_FAIL'

export const TVSHOW_DETAILS_REQUEST = 'TVSHOW_DETAILS_REQUEST'
export const TVSHOW_DETAILS_SUCCESS = 'TVSHOW_DETAILS_SUCCESS'
export const TVSHOW_DETAILS_FAIL = 'TVSHOW_DETAILS_FAIL'

export const GET_TVSHOW_CREDITS = 'GET_TVSHOW_CREDITS'
export const GET_TVSHOW_VIDEOS = 'GET_TVSHOW_VIDEOS'
export const GET_TVSHOW_IMAGES = 'GET_TVSHOW_IMAGES'

export const GET_TVSHOW_RECOMMENDATIONS = 'GET_SIMILAR_MOVIES'
